import { Album, Tracks } from "app/types";
import { create } from "zustand";

interface AlbumState {
  selectedAlbum: Album;
  selectedSong: Tracks;
  setSelectedAlbum: (album: Album) => void;
  setSelectedSong: (song: Tracks) => void;
}

export const useAlbumStore = create<AlbumState>((set) => ({
  selectedAlbum: {
    "title": "System of a Down",
    "release_year": 1998,
    "description": "Álbum debut de la banda que combina metal alternativo, punk y música armenia con letras políticas y sociales. Producido por Rick Rubin.",
    "tracks": [
      {
        "title": "Suite-Pee",
        "lyrics": "I had an out of body experience\nThe other day her name was jesus\nAnd for her everyone cried\nEveryone cried, everyone cried\n\nTry her philosophy, try her philosophy\nTry her philosophy, try!\nYou die for her philosophy, die for her philosophy\nDie her philosophy, die\n\nCrossed and terrored ravages of architecture\nLed me thy blades\nWe're crossed and terrored ravages of architecture\nHoist around the spade\n\nTry her philosophy, try her philosophy\nTry her philosophy, try!\nYou die for her philosophy, die for her philosophy\nDie her philosophy, die\n\nDie!\nDie!\nDie!\nWhy?!\n\nLie naked on the floor and\nLet the messiah go through our souls\nLie naked on the floor and\nLet the messiah go all through our souls\n\nDie (like a mother fucker)\nDie (like a mother fucker)\nDie (like a mother fucker)\nWhy? (Like a mother fucker)\n\nI want to fuck my way to the garden\n'Cause everyone needs a mother fucker\n\nThe following of a Christ\nThe following of a Christ\nThe following of a Christ\nThe following of a Christ\n\nThe falling of Christ\nThe falling of Christ\nThe falling of Christ\nThe falling of Christ"
      },
      {
        "title": "Know",
        "lyrics": "Cursed Earth\nCursed Earth\nCursed Earth\nCursed Earth\n\nI will never feed off the evergreen luster of your heart\nAll because we all live in the valley of the walls\nWhen they speak, we can peak from the windows of their mouths\nTo see the land, the women chant as they fly up to the sun\n\nYou never think you know why\nKnow, you never think you know why\nKnow, ever think you know why\nDon't know, don't\n\nBooks all say different things while people flap their yellow wings\nTrying to soar, being a whore of life and almost everything\nSheep that ran off from the herd, maybe dead\nNow's a bird, able to fly, able to die, able to fuck your mother's Earth\n\nYou never think you know why\nKnow, you never think you know why\nKnow, ever think you know why\n\nOn the other side, the other side\nThe other side\n\nDo you ever try to fly, do you ever try to fly?\nHave you ever wanted to die, have you ever wanted to die?\nDon't ever try to fly, don't ever try to fly\nDon't ever try to fly, unless you leave your body on the other side\n\nNever try to die, d'you ever try to die?\nKnow, you never think you know why\nKnow, you never think you know why\nKnow, you never think you know why\nKnow, ever think you know why\nKnow"
      },
      {
        "title": "Sugar",
        "lyrics": "The Kombucha mushroom people\nSitting around all day\nWho can believe you?\nWho can believe you?\nLet your mother pray\n\nSugar\nSugar\n\nI'm not there all the time, you know\nSome people, some people, some people\nCall it insane, yeah, they call it insane (sugar)\n\nI play Russian Roulette everyday, a man's sport\nWith a bullet called life, yeah, mama, called life (sugar)\n\nYou know that every time I try to go\nWhere I really wanna be\nIt's already where I am\n'Cause I'm already there\n\nThe Kombucha mushroom people\nSitting around all day\nWho can believe you?\nWho can believe you?\nLet your mother pray\n\nSugar\n\nI got a gun the other day from Sako\nIt's cute, small, fits right in my pocket\nYeah, right in my pocket (sugar)\n\nMy girl, you know, she lashes out at me sometimes\nAnd I just fucking kick her, and then, ooh baby, she's okay (sugar)\n\nPeople are always chasing me down\nTrying to push my face to the ground\nWhere all they do is suck out my motherfucking brains, my brains (sugar)\n\nThe Kombucha mushroom people\nSitting around all day\nWho can believe you?\nWho can believe you?\nLet your mother pray\n\nI sit, in my desolate room\nNo lights, no music\nJust anger\nI've killed everyone\nI'm away forever, but I'm feeling better\n\nHow do I feel?\nWhat do I say?\nFuck you, it all goes away\n\nHow do I feel?\nWhat do I say?\nFuck you, it all goes away\n\nHow do I feel?\nWhat do I say?\nIn the end it all goes away\n\nHow do I feel?\nWhat do I say?\nIn the end it all goes away\n\nHow do I feel?\nWhat do I say?\nIn the end it all goes away\n\nHow do I feel?\nWhat do I say?\nIn the end it all goes away\n\nHow do I feel?\nWhat do I say?\nIn the end it all goes away\n\nHow do I feel?\nWhat do I say?\nIn the end it all goes away\n\nIn the end it all goes away\nIn the end it all goes away\nIn the end it all goes away\nIn the end it all goes away\nIn the end it all goes away"
      },
      {
        "title": "Suggestions",
        "lyrics": "Watching from a post up high\nFrom where you see the ships afar\nFrom a well-trained eye\nThe waves all keep on crashing by\n\nIf you are the light post\nThen you own the working class\nBut if you want the answers\nYou better give a piece of ass!\nGive a piece of your ass\n\nWarning, post hypnotic suggestions\nRunning the ships ashore\nThe orange light that follows\nWill soon proclaim itself a god\n\nIf you point your questions\nThe fog will surely chew you up\nBut if you want the answers\nYou better get ready for the fire!\nReady for the fire\n\nThe ships are multiplying day after day, sir\nAnd they're coming close to the shore, sir, shore, sir\nWe need to evacuate the light post\nIt's all over, over\nIt's all over..."
      },
      {
        "title": "Spiders",
        "lyrics": "The piercing, radiant moon\nThe storming of poor June\nAll the life running through her hair\n\nApproaching guiding light\nOur shallow years in fright\nDreams are made, winding through my head\nThrough my head\n\nBefore you know, awake\nYour lives are open wide\nThe V-chip gives them sight\nOf all the life running through her hair\n\nThe spiders all in tune\nThe evening of the moon\nDreams are made, winding through my head\nThrough my head\n\nBefore you know, awake\nThrough my head\nThrough my head\nBefore you know\n\nBefore you know, I will be waiting, all awake\nDreams are made, winding through her hair\nDreams are made, winding through her hair"
      },
      {
        "title": "DDevil",
        "lyrics": "Plagiarized existence exist\nAmong the writers of the word\n\nShake your spear at Shakespeare\nShake your spear at Shakespeare\n\nLoud and noisy\nStrong refrigerators\n\nGaining independence\nGaining independence\n\nStupid people do stupid things\nSmart people outsmart each other\nThen themselves, then themselves\nThen themselves, then themselves\n\nTake me down there\nPhotographic relapse\nPeople feeding frenzy\nThe devil is so lovely\nThe devil is so lovely\nThe devil is so lovely\nSo lovely\nSo lovely\n\nMy blue moon rivets in exits\nForewarned customary spirits\nBy myself, by myself\nBy myself, by myself\n\nTake me down there\nPhotographic relapse\nPeople feeding frenzy\nThe devil is so lovely\n\nTake me down there\nPhotographic relapse\nPeople feeding frenzy\nThe devil is so lovely"
      },
      {
        "title": "Soil",
        "lyrics": "The phoenix he helped create\nOut of control boy without a dad\nShot the gun that startled my life\nWhile I drove him with a forty-five\n\nFriends for years, images in red\nBlew off his own motherfucking head\nConfidence, death, insecurity\nYour men fall unrealized\n\nUnrealized, unrealized\n\nMaking a decision of death\nWhile everyone around you plead\nThat you fly in peace\nI hope, my friend\n\nA man can't avoid what he's meant to do\nWhen he's meant to do it\nEven if he doesn't really want to\n\nMy memories are of fun and friendship\nOf weakness within the strength of youth\nFor reasons undefined, reasons undefined\nReasons undefined, reasons undefined\n\nFriends for years, images in red\nBlew off his own motherfucking head\nConfidence, death, insecurity\nYour men fall unrealized\n\nDon't you realize evil lives in the motherfucking skin?\nDon't you realize that evil lives in the motherfucking skin?\nDon't you realize that evil lives in the motherfucking skin?\nDon't you realize that evil lives in the skin?\nDon't you realize evil lives in the motherfucking skin?\nDon't you realize that evil lives in the motherfucking skin?\n\nWhy the fuck did you take him away from us, you motherfucker-fucker-fucker-fucker"
      },
      {
        "title": "War?",
        "lyrics": "Dark is the light\nThe man you fight\nWith all your prayers, incantations\nRunning away, a trivial day\nOf judgment and deliverance\n\nTo whom was sold, this bounty soul\nA gentile or a priest?\nWho victored over, the Seljuks\nWhen the holy land was taken\n\nWe will fight the heathens, we will fight the heathens\nWe will fight the heathens, we will fight the heathens\n\nWas it the riches, of the land\nPowers of bright darkness\nThat lead the noble, to the East\nTo fight the heathens\n\nWe will fight the heathens, we will fight the heathens\nWe will fight the heathens, we will fight the heathens\nNo, we will fight the heathens, we will fight the heathens\nNo, we will fight the heathens, we will fight the heathens\n\nWe must call upon our bright darkness\nBeliefs, they're the bullets of the wicked\nFor you must enter a room to destroy it\nNo international security\n\nNo call of the righteous man\nNeeds a reason to kill man\nHistory teaches us so\nThe reason he must attain\nMust be approved by his God\nHis child, partisan brother of war\n\nOf war, we don't speak any more of war\nWe don't speak any more of war\nWe don't speak any more of war\nWe don't speak anymore\n\nWe will fight the heathens, we will fight the heathens\nWe will fight the heathens, we will fight the heathens\nNo, we will fight the heathens, we will fight the heathens\nNo, we will fight the heathens, we will fight the heathens"
      },
      {
        "title": "Mind",
        "lyrics": "Oh baby, come close to me\nLet me love you\nOh baby, come close to me\nLet me feel you\n\nLook at each other\nLook at each other\nLook at each other\nLook at each other\nLook at each other\nLook at each other\nLook at each other\nLook at each other\n\nGo away\nGo away\nGo away\nGo away\n\nWell now, mutually\nMentally molested\nChildren of a mother\nMutually, mentally molested\nChildren of sin\n\nOh no, the ever so popular\nBeating that took you under\nOh no, the ever so popular\nBeating that broke your skin\n\nFree thinkers are dangerous\nBlame, hate\nFor fate's seed\n\nGo away\nGo away\nGo away\nGo away\n\nWell, you need the ones you love\nLove the ones that you need\nNeed the ones you love\nAnd love the ones you bleed\n\nLives rearranged and lives in my range\nCan you see?\nLives rearranged and lives in my range\nCan you see?\n\nFree thinkers are dangerous\nBlame, hate\nFor fate's seed\n\nDie!\nDie!\nDie!\nDie!\n\nGonna let you motherfuckers die\nGonna let you motherfuckers die\nGonna let you motherfuckers die\nGonna let you motherfuckers die\n\nLook at each other\nLook at each other\nLook at each other"
      },
      {
        "title": "Peephole",
        "lyrics": "When your stars are...\nAnd your rivers fly\nDo you ever believe you were stuck in the sky?\nWhen your...\n\nWhen your stars are baked and your rivers fly\nDo you ever believe you were stuck in the sky?\nWhen your castle breaks and your feet are dry\nDo you ever believe you were stuck in the sky?\n\nDo you believe, when you're high\nThat your life is tried?\n\nDon't you ever get stuck in the sky\nDon't you ever get stuck in the sky\nDon't ever get stuck in the sky when you're high\n\nWhen your moon is fake and your mermaids cry\nDo you ever believe you were stuck in the sky?\nWhen your tunnel fades and your guide is shy\nDo you ever believe you were stuck out in the sky?\n\nDo you believe, when you're high\nThat your life is tried?\n\nDon't you ever get stuck in the sky\nDon't you ever get stuck in the sky\nDon't ever get stuck in the sky when you're high\nDon't you ever get stuck in the sky\nDon't you ever get stuck in the sky\nDon't ever get stuck in the sky when you're high\nDon't you ever get stuck in the sky\nDon't you ever get stuck in the sky\nDon't you ever get stuck in the sky\nDon't you ever get stuck in the sky\nDon't you ever get stuck in the sky\nDon't you ever get stuck in the sky\nDon't ever get stuck in the sky when you're high"
      },
      {
        "title": "CUBErt",
        "lyrics": "Pre-flight delight\nDefaced street lights\nA pyramid mind fuck\nDon't leave your seats now\n\nPopcorn everywhere, canned\nCliche people organs rare\nCorn everywhere canned\nCliche people cannot dare, dare\nDare, dare\n\nI want to be\nA fallen ruby\nGuest vibrations\nDon't leave your seats now\n\nHumans everywhere, canned\nClike people organs rare\nHumans everywhere, canned\nCliche people cannot dare, dare\nDare, dare\n\nHumans everywhere, canned\nCliche people organs rare\nHumans everywhere, canned\nCliche people cannot dare\n\nHumans everywhere, canned\nCliche people organs rare\nHumans everywhere, canned\nCliche people cannot dare, dare\nDare, dare"
      },
      {
        "title": "Darts",
        "lyrics": "May I please remain in this space\nFor darts screech by my desires\nMay I please remain in this space\nFor darts screech by my desires\n\nArt thou, not human man, art thou\nNot human man, art thou\nNot human man, art thou\nNot human man, art thou\nNot human man, art thou\nNot human man, art thou\nNot human man, art thou\nHuman man art thou...\n\nLife-threatening lifestyles\nA hitman, a nun; lovers\nLife-threatening lifestyles\nA hitman, a nun; lovers\n\nArise as did the Gods Ninti\nArise as did the Gods Ninti\nArise as did the Gods Ninti\nAnd Ishkur\n\nClock men, for they will fail\nFear not the Gods that come from the sky\nLong not for the one who've lost their way\nLong not for the one who've lost their way\n\nArise as did the Gods Ninti\nArise as did the Gods Ninti\nArise as did the Gods Ninti\nAnd Ishkur, Ishkur, motherfucker\n\nCan you tell me\nI don't know"
      },
      {
        "title": "P.L.U.C.K.",
        "lyrics": "Elimination\nElimination\nElimination\nDie!\nWhy?\nWalk down! (Walk down!)\n\nA whole race, genocide\nTaken away all of our pride\nA whole race, genocide\nTaken away, watch them all fall down!\n\nRevolution, the only solution\nThe armed response of an entire nation\nRevolution, the only solution\nWe've taken all your shit, now it's time for restitution\n\nRecognition, restoration, reparation\nRecognition, restoration, reparation\nWatch them all fall down!\n\nRevolution, the only solution\nThe armed response of an entire nation\nRevolution, the only solution\nWe've taken all your shit, now it's time for restitution\n\nThe plan was mastered and called \"Genocide\" (Never want to see you 'round)\nYou took all the children and then we died (Never want to see you 'round)\nThe few that remained were never found (Never want to see you 'round)\nAll in a system\n\nDown!\nDown!\nDown!\nDown!\nWalk down!\nWalk down!\n\nWatch them all fall down!\n\nRevolution, the only solution\nThe armed response of an entire nation\nRevolution, the only solution\nWe've taken all your shit, now it's time for restitution\n\nThe plan was mastered and called \"Genocide\" (Never want to see you 'round)\nYou took all the children and then we died (Never want to see you 'round)\nThe few that remained were never found, (Never want to see you 'round)\nAll in a system, down"
      }
    ]
  },
  selectedSong: {
    title: "Suite-Pee",
    lyrics: "I had an out of body experience\nThe other day her name was jesus\nAnd for her everyone cried\nEveryone cried, everyone cried\n\nTry her philosophy, try her philosophy\nTry her philosophy, try!\nYou die for her philosophy, die for her philosophy\nDie her philosophy, die\n\nCrossed and terrored ravages of architecture\nLed me thy blades\nWe're crossed and terrored ravages of architecture\nHoist around the spade\n\nTry her philosophy, try her philosophy\nTry her philosophy, try!\nYou die for her philosophy, die for her philosophy\nDie her philosophy, die\n\nDie!\nDie!\nDie!\nWhy?!\n\nLie naked on the floor and\nLet the messiah go through our souls\nLie naked on the floor and\nLet the messiah go all through our souls\n\nDie (like a mother fucker)\nDie (like a mother fucker)\nDie (like a mother fucker)\nWhy? (Like a mother fucker)\n\nI want to fuck my way to the garden\n'Cause everyone needs a mother fucker\n\nThe following of a Christ\nThe following of a Christ\nThe following of a Christ\nThe following of a Christ\n\nThe falling of Christ\nThe falling of Christ\nThe falling of Christ\nThe falling of Christ",
  },
  setSelectedAlbum: (album) => set({ selectedAlbum: album }),
  setSelectedSong: (song) => set({ selectedSong: song }),
}));
